// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPlanUpdateNotifier is an autogenerated mock type for the PlanUpdateNotifier type
type MockPlanUpdateNotifier struct {
	mock.Mock
}

type MockPlanUpdateNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlanUpdateNotifier) EXPECT() *MockPlanUpdateNotifier_Expecter {
	return &MockPlanUpdateNotifier_Expecter{mock: &_m.Mock}
}

// NotifyPlanUpdated provides a mock function with given fields: ctx, userID, activePlan, prevPlan, subscription
func (_m *MockPlanUpdateNotifier) NotifyPlanUpdated(ctx context.Context, userID string, activePlan string, prevPlan string, subscription interface{}) error {
	ret := _m.Called(ctx, userID, activePlan, prevPlan, subscription)

	if len(ret) == 0 {
		panic("no return value specified for NotifyPlanUpdated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, interface{}) error); ok {
		r0 = rf(ctx, userID, activePlan, prevPlan, subscription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPlanUpdateNotifier_NotifyPlanUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyPlanUpdated'
type MockPlanUpdateNotifier_NotifyPlanUpdated_Call struct {
	*mock.Call
}

// NotifyPlanUpdated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - activePlan string
//   - prevPlan string
//   - subscription interface{}
func (_e *MockPlanUpdateNotifier_Expecter) NotifyPlanUpdated(ctx interface{}, userID interface{}, activePlan interface{}, prevPlan interface{}, subscription interface{}) *MockPlanUpdateNotifier_NotifyPlanUpdated_Call {
	return &MockPlanUpdateNotifier_NotifyPlanUpdated_Call{Call: _e.mock.On("NotifyPlanUpdated", ctx, userID, activePlan, prevPlan, subscription)}
}

func (_c *MockPlanUpdateNotifier_NotifyPlanUpdated_Call) Run(run func(ctx context.Context, userID string, activePlan string, prevPlan string, subscription interface{})) *MockPlanUpdateNotifier_NotifyPlanUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(interface{}))
	})
	return _c
}

func (_c *MockPlanUpdateNotifier_NotifyPlanUpdated_Call) Return(_a0 error) *MockPlanUpdateNotifier_NotifyPlanUpdated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlanUpdateNotifier_NotifyPlanUpdated_Call) RunAndReturn(run func(context.Context, string, string, string, interface{}) error) *MockPlanUpdateNotifier_NotifyPlanUpdated_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlanUpdateNotifier creates a new instance of MockPlanUpdateNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlanUpdateNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlanUpdateNotifier {
	mock := &MockPlanUpdateNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
