// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSubscriptionLoader is an autogenerated mock type for the SubscriptionLoader type
type MockSubscriptionLoader struct {
	mock.Mock
}

type MockSubscriptionLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionLoader) EXPECT() *MockSubscriptionLoader_Expecter {
	return &MockSubscriptionLoader_Expecter{mock: &_m.Mock}
}

// GetActiveUserPlans provides a mock function with given fields: ctx
func (_m *MockSubscriptionLoader) GetActiveUserPlans(ctx context.Context) (map[string]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveUserPlans")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionLoader_GetActiveUserPlans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveUserPlans'
type MockSubscriptionLoader_GetActiveUserPlans_Call struct {
	*mock.Call
}

// GetActiveUserPlans is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSubscriptionLoader_Expecter) GetActiveUserPlans(ctx interface{}) *MockSubscriptionLoader_GetActiveUserPlans_Call {
	return &MockSubscriptionLoader_GetActiveUserPlans_Call{Call: _e.mock.On("GetActiveUserPlans", ctx)}
}

func (_c *MockSubscriptionLoader_GetActiveUserPlans_Call) Run(run func(ctx context.Context)) *MockSubscriptionLoader_GetActiveUserPlans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSubscriptionLoader_GetActiveUserPlans_Call) Return(_a0 map[string]int, _a1 error) *MockSubscriptionLoader_GetActiveUserPlans_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionLoader_GetActiveUserPlans_Call) RunAndReturn(run func(context.Context) (map[string]int, error)) *MockSubscriptionLoader_GetActiveUserPlans_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionLoader creates a new instance of MockSubscriptionLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionLoader {
	mock := &MockSubscriptionLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
