// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entitlements "github.com/grantsy/grantsy/internal/entitlements"
	mock "github.com/stretchr/testify/mock"
)

// MockPricingProvider is an autogenerated mock type for the PricingProvider type
type MockPricingProvider struct {
	mock.Mock
}

type MockPricingProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPricingProvider) EXPECT() *MockPricingProvider_Expecter {
	return &MockPricingProvider_Expecter{mock: &_m.Mock}
}

// GetPlanVariants provides a mock function with given fields: planID
func (_m *MockPricingProvider) GetPlanVariants(planID string) []entitlements.VariantDTO {
	ret := _m.Called(planID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlanVariants")
	}

	var r0 []entitlements.VariantDTO
	if rf, ok := ret.Get(0).(func(string) []entitlements.VariantDTO); ok {
		r0 = rf(planID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entitlements.VariantDTO)
		}
	}

	return r0
}

// MockPricingProvider_GetPlanVariants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlanVariants'
type MockPricingProvider_GetPlanVariants_Call struct {
	*mock.Call
}

// GetPlanVariants is a helper method to define mock.On call
//   - planID string
func (_e *MockPricingProvider_Expecter) GetPlanVariants(planID interface{}) *MockPricingProvider_GetPlanVariants_Call {
	return &MockPricingProvider_GetPlanVariants_Call{Call: _e.mock.On("GetPlanVariants", planID)}
}

func (_c *MockPricingProvider_GetPlanVariants_Call) Run(run func(planID string)) *MockPricingProvider_GetPlanVariants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPricingProvider_GetPlanVariants_Call) Return(_a0 []entitlements.VariantDTO) *MockPricingProvider_GetPlanVariants_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPricingProvider_GetPlanVariants_Call) RunAndReturn(run func(string) []entitlements.VariantDTO) *MockPricingProvider_GetPlanVariants_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPricingProvider creates a new instance of MockPricingProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPricingProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPricingProvider {
	mock := &MockPricingProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
