// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	subscriptions "github.com/grantsy/grantsy/internal/subscriptions"
	mock "github.com/stretchr/testify/mock"
)

// MockSubscriptionReader is an autogenerated mock type for the SubscriptionReader type
type MockSubscriptionReader struct {
	mock.Mock
}

type MockSubscriptionReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionReader) EXPECT() *MockSubscriptionReader_Expecter {
	return &MockSubscriptionReader_Expecter{mock: &_m.Mock}
}

// GetSubscriptionByUserID provides a mock function with given fields: ctx, userID
func (_m *MockSubscriptionReader) GetSubscriptionByUserID(ctx context.Context, userID string) (*subscriptions.Subscription, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionByUserID")
	}

	var r0 *subscriptions.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*subscriptions.Subscription, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *subscriptions.Subscription); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*subscriptions.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionReader_GetSubscriptionByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionByUserID'
type MockSubscriptionReader_GetSubscriptionByUserID_Call struct {
	*mock.Call
}

// GetSubscriptionByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockSubscriptionReader_Expecter) GetSubscriptionByUserID(ctx interface{}, userID interface{}) *MockSubscriptionReader_GetSubscriptionByUserID_Call {
	return &MockSubscriptionReader_GetSubscriptionByUserID_Call{Call: _e.mock.On("GetSubscriptionByUserID", ctx, userID)}
}

func (_c *MockSubscriptionReader_GetSubscriptionByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockSubscriptionReader_GetSubscriptionByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSubscriptionReader_GetSubscriptionByUserID_Call) Return(_a0 *subscriptions.Subscription, _a1 error) *MockSubscriptionReader_GetSubscriptionByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionReader_GetSubscriptionByUserID_Call) RunAndReturn(run func(context.Context, string) (*subscriptions.Subscription, error)) *MockSubscriptionReader_GetSubscriptionByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionReader creates a new instance of MockSubscriptionReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionReader {
	mock := &MockSubscriptionReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
