// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	subscriptions "github.com/grantsy/grantsy/internal/subscriptions"
	mock "github.com/stretchr/testify/mock"
)

// MockPriceFetcher is an autogenerated mock type for the PriceFetcher type
type MockPriceFetcher struct {
	mock.Mock
}

type MockPriceFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPriceFetcher) EXPECT() *MockPriceFetcher_Expecter {
	return &MockPriceFetcher_Expecter{mock: &_m.Mock}
}

// GetPrice provides a mock function with given fields: ctx, priceID
func (_m *MockPriceFetcher) GetPrice(ctx context.Context, priceID int) (*subscriptions.PriceInfo, error) {
	ret := _m.Called(ctx, priceID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrice")
	}

	var r0 *subscriptions.PriceInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*subscriptions.PriceInfo, error)); ok {
		return rf(ctx, priceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *subscriptions.PriceInfo); ok {
		r0 = rf(ctx, priceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*subscriptions.PriceInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, priceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPriceFetcher_GetPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrice'
type MockPriceFetcher_GetPrice_Call struct {
	*mock.Call
}

// GetPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - priceID int
func (_e *MockPriceFetcher_Expecter) GetPrice(ctx interface{}, priceID interface{}) *MockPriceFetcher_GetPrice_Call {
	return &MockPriceFetcher_GetPrice_Call{Call: _e.mock.On("GetPrice", ctx, priceID)}
}

func (_c *MockPriceFetcher_GetPrice_Call) Run(run func(ctx context.Context, priceID int)) *MockPriceFetcher_GetPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockPriceFetcher_GetPrice_Call) Return(_a0 *subscriptions.PriceInfo, _a1 error) *MockPriceFetcher_GetPrice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPriceFetcher_GetPrice_Call) RunAndReturn(run func(context.Context, int) (*subscriptions.PriceInfo, error)) *MockPriceFetcher_GetPrice_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPriceFetcher creates a new instance of MockPriceFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPriceFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPriceFetcher {
	mock := &MockPriceFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
