// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWebhookVerifier is an autogenerated mock type for the WebhookVerifier type
type MockWebhookVerifier struct {
	mock.Mock
}

type MockWebhookVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebhookVerifier) EXPECT() *MockWebhookVerifier_Expecter {
	return &MockWebhookVerifier_Expecter{mock: &_m.Mock}
}

// VerifyWebhook provides a mock function with given fields: ctx, signature, body
func (_m *MockWebhookVerifier) VerifyWebhook(ctx context.Context, signature string, body []byte) bool {
	ret := _m.Called(ctx, signature, body)

	if len(ret) == 0 {
		panic("no return value specified for VerifyWebhook")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) bool); ok {
		r0 = rf(ctx, signature, body)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockWebhookVerifier_VerifyWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyWebhook'
type MockWebhookVerifier_VerifyWebhook_Call struct {
	*mock.Call
}

// VerifyWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - signature string
//   - body []byte
func (_e *MockWebhookVerifier_Expecter) VerifyWebhook(ctx interface{}, signature interface{}, body interface{}) *MockWebhookVerifier_VerifyWebhook_Call {
	return &MockWebhookVerifier_VerifyWebhook_Call{Call: _e.mock.On("VerifyWebhook", ctx, signature, body)}
}

func (_c *MockWebhookVerifier_VerifyWebhook_Call) Run(run func(ctx context.Context, signature string, body []byte)) *MockWebhookVerifier_VerifyWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockWebhookVerifier_VerifyWebhook_Call) Return(_a0 bool) *MockWebhookVerifier_VerifyWebhook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookVerifier_VerifyWebhook_Call) RunAndReturn(run func(context.Context, string, []byte) bool) *MockWebhookVerifier_VerifyWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebhookVerifier creates a new instance of MockWebhookVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebhookVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebhookVerifier {
	mock := &MockWebhookVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
