// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	subscriptions "github.com/grantsy/grantsy/internal/subscriptions"
	mock "github.com/stretchr/testify/mock"
)

// MockSubscriptionWriter is an autogenerated mock type for the SubscriptionWriter type
type MockSubscriptionWriter struct {
	mock.Mock
}

type MockSubscriptionWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionWriter) EXPECT() *MockSubscriptionWriter_Expecter {
	return &MockSubscriptionWriter_Expecter{mock: &_m.Mock}
}

// UpsertSubscription provides a mock function with given fields: ctx, sub
func (_m *MockSubscriptionWriter) UpsertSubscription(ctx context.Context, sub *subscriptions.Subscription) error {
	ret := _m.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *subscriptions.Subscription) error); ok {
		r0 = rf(ctx, sub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubscriptionWriter_UpsertSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertSubscription'
type MockSubscriptionWriter_UpsertSubscription_Call struct {
	*mock.Call
}

// UpsertSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - sub *subscriptions.Subscription
func (_e *MockSubscriptionWriter_Expecter) UpsertSubscription(ctx interface{}, sub interface{}) *MockSubscriptionWriter_UpsertSubscription_Call {
	return &MockSubscriptionWriter_UpsertSubscription_Call{Call: _e.mock.On("UpsertSubscription", ctx, sub)}
}

func (_c *MockSubscriptionWriter_UpsertSubscription_Call) Run(run func(ctx context.Context, sub *subscriptions.Subscription)) *MockSubscriptionWriter_UpsertSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*subscriptions.Subscription))
	})
	return _c
}

func (_c *MockSubscriptionWriter_UpsertSubscription_Call) Return(_a0 error) *MockSubscriptionWriter_UpsertSubscription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscriptionWriter_UpsertSubscription_Call) RunAndReturn(run func(context.Context, *subscriptions.Subscription) error) *MockSubscriptionWriter_UpsertSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionWriter creates a new instance of MockSubscriptionWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionWriter {
	mock := &MockSubscriptionWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
