// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPlanProvider is an autogenerated mock type for the PlanProvider type
type MockPlanProvider struct {
	mock.Mock
}

type MockPlanProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlanProvider) EXPECT() *MockPlanProvider_Expecter {
	return &MockPlanProvider_Expecter{mock: &_m.Mock}
}

// GetUserFeatures provides a mock function with given fields: userID
func (_m *MockPlanProvider) GetUserFeatures(userID string) []string {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserFeatures")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockPlanProvider_GetUserFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserFeatures'
type MockPlanProvider_GetUserFeatures_Call struct {
	*mock.Call
}

// GetUserFeatures is a helper method to define mock.On call
//   - userID string
func (_e *MockPlanProvider_Expecter) GetUserFeatures(userID interface{}) *MockPlanProvider_GetUserFeatures_Call {
	return &MockPlanProvider_GetUserFeatures_Call{Call: _e.mock.On("GetUserFeatures", userID)}
}

func (_c *MockPlanProvider_GetUserFeatures_Call) Run(run func(userID string)) *MockPlanProvider_GetUserFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPlanProvider_GetUserFeatures_Call) Return(_a0 []string) *MockPlanProvider_GetUserFeatures_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlanProvider_GetUserFeatures_Call) RunAndReturn(run func(string) []string) *MockPlanProvider_GetUserFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPlan provides a mock function with given fields: userID
func (_m *MockPlanProvider) GetUserPlan(userID string) string {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPlan")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPlanProvider_GetUserPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPlan'
type MockPlanProvider_GetUserPlan_Call struct {
	*mock.Call
}

// GetUserPlan is a helper method to define mock.On call
//   - userID string
func (_e *MockPlanProvider_Expecter) GetUserPlan(userID interface{}) *MockPlanProvider_GetUserPlan_Call {
	return &MockPlanProvider_GetUserPlan_Call{Call: _e.mock.On("GetUserPlan", userID)}
}

func (_c *MockPlanProvider_GetUserPlan_Call) Run(run func(userID string)) *MockPlanProvider_GetUserPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPlanProvider_GetUserPlan_Call) Return(_a0 string) *MockPlanProvider_GetUserPlan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlanProvider_GetUserPlan_Call) RunAndReturn(run func(string) string) *MockPlanProvider_GetUserPlan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlanProvider creates a new instance of MockPlanProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlanProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlanProvider {
	mock := &MockPlanProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
