// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSubscriptionObserver is an autogenerated mock type for the SubscriptionObserver type
type MockSubscriptionObserver struct {
	mock.Mock
}

type MockSubscriptionObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionObserver) EXPECT() *MockSubscriptionObserver_Expecter {
	return &MockSubscriptionObserver_Expecter{mock: &_m.Mock}
}

// OnSubscriptionChange provides a mock function with given fields: ctx, userID, productID, active, subscription
func (_m *MockSubscriptionObserver) OnSubscriptionChange(ctx context.Context, userID string, productID int, active bool, subscription interface{}) error {
	ret := _m.Called(ctx, userID, productID, active, subscription)

	if len(ret) == 0 {
		panic("no return value specified for OnSubscriptionChange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, bool, interface{}) error); ok {
		r0 = rf(ctx, userID, productID, active, subscription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubscriptionObserver_OnSubscriptionChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnSubscriptionChange'
type MockSubscriptionObserver_OnSubscriptionChange_Call struct {
	*mock.Call
}

// OnSubscriptionChange is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - productID int
//   - active bool
//   - subscription interface{}
func (_e *MockSubscriptionObserver_Expecter) OnSubscriptionChange(ctx interface{}, userID interface{}, productID interface{}, active interface{}, subscription interface{}) *MockSubscriptionObserver_OnSubscriptionChange_Call {
	return &MockSubscriptionObserver_OnSubscriptionChange_Call{Call: _e.mock.On("OnSubscriptionChange", ctx, userID, productID, active, subscription)}
}

func (_c *MockSubscriptionObserver_OnSubscriptionChange_Call) Run(run func(ctx context.Context, userID string, productID int, active bool, subscription interface{})) *MockSubscriptionObserver_OnSubscriptionChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(bool), args[4].(interface{}))
	})
	return _c
}

func (_c *MockSubscriptionObserver_OnSubscriptionChange_Call) Return(_a0 error) *MockSubscriptionObserver_OnSubscriptionChange_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscriptionObserver_OnSubscriptionChange_Call) RunAndReturn(run func(context.Context, string, int, bool, interface{}) error) *MockSubscriptionObserver_OnSubscriptionChange_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionObserver creates a new instance of MockSubscriptionObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionObserver {
	mock := &MockSubscriptionObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
